### ISSUE TITLE
Cannot add dependencies in pom.xml.

### ISSUE THREAD

**Issue by yianpuodiaotu** [PredixDev/predix-websocket-client#2]
Hi all,
   I'm Java developer, and leaning predix recently. I can access  predio.io  normally through the address : https://login.system.aws-jp01-pr.ice.predix.io/login ,but when follow the guides i found I can not login in the page: https://artifactory.predix.io/artifactory/webapp/#/login. That leds to I cannot add dependency in pom.xml file. Is there an address for Japan?   or other things?
![image](https://user-images.githubusercontent.com/2845331/27369976-f5ba5d8a-568c-11e7-8f19-021af0fb269b.png)

**Comment by gstroup** [comment]
This is currently an issue for customers like you that are not using the US West PoP.  There are plans to unify predix.io into a single instance, which will solve this problem.  In the meantime, you can sign up for a free account in US West (www.predix.io) and use those credentials to access artifactory.  Sorry for the inconvenience.
