### ISSUE TITLE
Add authentication for proxy using username and password to WebSocketPoolableConnectionFactory

### ISSUE THREAD

**Issue by davenunn** [PredixDev/predix-websocket-client#4]
The WebSocketPoolableConnectionFactory does not implement setting the proxyUser and proxyPassword. Currently it only implements setting proxyServer and proxyPort.

My corporate proxy server requires authentication to access the Internet. There is no access without credentials (username and password) being supplied. I have tried many combinations of environment variables and settings (both in the OS and Eclipse) to provide this information but without success (the proxyServer and proxyPort settings are set correctly). This is preventing me from debugging Predix micro-services locally in Eclipse.

This should be straightforward to resolve by using the setCredentials method of the nv-websocket-client as described in the HttpProxy section here: https://github.com/TakahikoKawasaki/nv-websocket-client. This would be implemented in the detectAndSetProxy method of the WebSocketPoolableConnectionFactory class with changes to the configuration information to support the additional proxyUser and proxyPassword.

This is a continuation of Issue 3 (I don't believe my problem was understood). Thanks, Dave

**Comment by gstroup** [comment]
I can see that this issue was never addressed.  (Probably because our proxy server does not require username/password.)  If you see an easy solution, could you make a pull request??  If not, we'll try to address it soon.  Thanks.

**Comment by turnerth** [comment]
closing this issue in favor of the other issue.
